title: Futuristic Blue
description: A sleek, sci-fi inspired theme
baseurl: ""
url: "https://bulanadi-marklorence-04.github.io/sample-lang-po/"

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

author:
  name: "Bulanadi, Mark Lorence"
